### ISSUE TITLE
Herramientas de trabajo

### ISSUE THREAD

**Issue by MariaVictoria** [Innovacion-tec-4-0/Practica_Profesionalizante_I#1]
Definiremos herramientas de trabajo

**Comment by MariaVictoria** [comment]
Github

**Comment by Roryx1** [comment]
Wokwi

**Comment by ranitadelamatrix** [comment]
Arduino ide(en el caso de llevar a la realidad el se sensor)

**Comment by CesarLucasMartins** [comment]
Utilizaremos **TRELLO**: Es una herramienta de gestión de proyectos que utiliza tableros y tarjetas para organizar tareas y flujos de trabajo. Permite visualizar el progreso de las actividades y facilita la coordinación entre los miembros de un equipo.

**Comment by CesarLucasMartins** [comment]
Figma: diseño colaborativo en línea, creación de interfaces y gráficos. Permite a múltiples usuarios trabajar simultáneamente en un proyecto, lo que facilita la colaboración en el diseño de aplicaciones y sitios web, diagramas etc.
