### ISSUE TITLE
Revisar disponibilidad de sensores 

### ISSUE THREAD

**Issue by MariaVictoria** [Innovacion-tec-4-0/Practica_Profesionalizante_I#3]
Romina se encargará de verificar la disponibilidad de sensores en Wokwi

**Comment by Roryx1** [comment]
Temperatura y Humedad: DHT22. El sensor BME280 no se encuentra disponible en Wokwi. 
Sensor de calidad del aire MQ-135: No está disponible en la plataforma. No obstante, investigué y encontré un proyecto de Woki en el cual usan un potenciómetro para simular ese sensor.
Sensor de Luz BH1750: No está pero se puede emular. https://wokwi.com/projects/401567758260228097
Sensor PIR: Está incluido en Wokwi
En los proyectos que investigué en Wokwi, dentro del código se cargan las librerías aunque el sensor no esté disponible dentro de la solapa de ítems.
