### ISSUE TITLE
Sensore y actuadores

### ISSUE THREAD

**Issue by MariaVictoria** [Innovacion-tec-4-0/Practica_Profesionalizante_I#4]
Gastón verificará y dejará asentado sobre los sensores y actuadores que hemos elegido para el proyecto.

**Comment by ranitadelamatrix** [comment]
https://docs.google.com/document/d/1SYODT8eZCptLI9aFFdpsb44glh1ijroVx0uAlN6jEW8/edit?usp=drivesdk

Adjunto el link del documento sobre los sensores necesarios
