### ISSUE TITLE
Maquetado

### ISSUE THREAD

**Issue by MariaVictoria** [Innovacion-tec-4-0/Practica_Profesionalizante_I#5]
Santiago estudiará difentes opciones de maquetado y/o presentación de la propuesta y diagramado de sensores

**Comment by Ferreyra-Santiago** [comment]
Hola chicos buenas tardes chicos aca dejo toda informacion de las distintas opciones que encontre para tener en cuenta ala hora de hacer el  maquetado

les dejo toda la info en la wiki del proyecto

**Comment by MariaVictoria** [comment]
gracias
